### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by Nodarii** [ITsvetkoFF/angular-basic-example#1]
@ITsvetkoFF Please, restructure directory folding according to some best practice. 

For now it looks unextensible and chaotically

Here is the link for the structure example: https://scotch.io/tutorials/angularjs-best-practices-directory-structure#disqus_thread

**Comment by ITsvetkoFF** [comment]
@nadarik thanks for comment :) 
It will never be extended. It is only the sample application to show main parts step-by step. For good architecture we will have some other examples. :)   

But to be fair - separate views can be modules. This is a kind of feature-based app architecture, as I believe. How do you think? :)

**Comment by ITsvetkoFF** [comment]
Note that steps here are in separate branches.  The first one is finish-11. (finish minus eleven) 
sorry for such naming :)

**Comment by Nodarii** [comment]
@ITsvetkoFF I got it, but I thought it would be nice to show kind of best practices and "extensibility" based on you demo app.

**Comment by ITsvetkoFF** [comment]
Yep, I'll try my best.

**Comment by Nodarii** [comment]
thx
